FlipsideCrypto/base-models

- models/silver/base_goerli/methods/silver_goerli__receipts_method.sql
- models/silver/base_goerli/silver_goerli__blocks.sql
- models/silver/base_goerli/silver_goerli__logs.sql
- models/silver/base_goerli/silver_goerli__traces.sql
- models/silver/base_goerli/silver_goerli__transactions.sql
- models/silver/eth_goerli/silver__eth_goerli_block_ranges.sql
- models/silver/eth_goerli/silver__eth_goerli_logs.sql
- Update all models using `hex_to_int` using `public` or `ethereum.public` schema to `utils` schema
- Excludes models with `enabled = false`
> AN-3306/swap-public-to-utils

- .github/workflows/dbt_run_abi_refresh.yml
- .github/workflows/dbt_run_api_feeder_table.yml
- models/bronze/api_udf/bronze_api__contract_abis.sql
- models/bronze/api_udf/bronze_api__contract_abis.yml
- models/bronze/api_udf/bronze_api__token_reads.sql
- models/bronze/api_udf/bronze_api__token_reads.yml
- models/silver/API_udf/silver__relevant_abi_contracts.sql
- models/silver/API_udf/silver__relevant_abi_contracts.yml
- models/silver/API_udf/silver__relevant_contracts.sql
- models/silver/API_udf/silver__relevant_contracts.yml
- models/silver/abis/silver__abis.sql
- models/silver/abis/silver__abis.yml
- models/silver/abis/silver__bytecode_abis.sql
- models/silver/abis/silver__bytecode_abis.yml
- models/silver/abis/silver__complete_event_abis.sql
- models/silver/abis/silver__complete_event_abis.yml
- models/silver/abis/silver__override_abis.sql
- models/silver/abis/silver__proxies.sql
- models/silver/abis/silver__proxies.yml
- models/silver/abis/silver__user_verified_abis.sql
- models/silver/abis/silver__user_verified_abis.yml
- models/silver/abis/silver__verified_abis.sql
- models/silver/abis/silver__verified_abis.yml
- models/silver/contracts/silver__contracts.sql
- models/silver/contracts/silver__contracts.yml
- models/silver/contracts/silver__created_contracts.sql
- models/silver/contracts/silver__created_contracts.yml
- models/sources.yml
- adds abi and contracts pipelines
> contract and abis pipeline

- .github/workflows/dbt_run_incremental.yml
- .github/workflows/dbt_run_streamline_decoder.yml
- models/gold/core/core__ez_decoded_event_logs.sql
- models/gold/core/core__ez_decoded_event_logs.yml
- models/gold/core/core__fact_decoded_event_logs.sql
- models/gold/core/core__fact_decoded_event_logs.yml
- models/silver/core/silver__decoded_logs.sql
- models/silver/core/silver__decoded_logs.yml
- adds decoded logs to silver and gold
> release decoded logs

- .github/workflows/dbt_test_daily.yml
- .github/workflows/dbt_test_intraday.yml
- .github/workflows/dbt_test_monthly.yml
- migrate workflows back to `dbt_test` warehouse
> move to dbt test

- models/doc_descriptions/dex - (imported from layer 1)/eth_dex_lp_table_doc.md
- models/doc_descriptions/dex - (imported from layer 1)/eth_ez_dex_swaps_table_doc.md
- models/gold/defi/defi__dim_dex_liquidity_pools.sql
- models/gold/defi/defi__ez_dex_swaps.sql
- models/silver/defi/dex/dackieswap/silver_dex__dackie_pools.sql
- models/silver/defi/dex/dackieswap/silver_dex__dackie_pools.yml
- models/silver/defi/dex/dackieswap/silver_dex__dackie_swaps.sql
- models/silver/defi/dex/dackieswap/silver_dex__dackie_swaps.yml
- models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql
- models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
- models/silver/defi/dex/woofi/silver_dex__woofi_swaps.sql
- models/silver/defi/dex/woofi/silver_dex__woofi_swaps.yml
Add two additional dexes:
- Dackieswap
- Woofi
> AN-3767/Add-additional-base-dexes

- models/doc_descriptions/nft/nft_event_index.md
- models/doc_descriptions/nft/nft_nft_from_address.md
- models/doc_descriptions/nft/nft_nft_to_address.md
- models/gold/nft/core__ez_nft_transfers.yml
- models/gold/nft/nft__ez_nft_transfers.yml
- models/silver/nft/silver__complete_nft_sales.sql
- models/silver/nft/silver__zeroex_sales.sql
- models/silver/nft/silver__zeroex_sales.yml
1. Add 0x marketplace to Base - Coinbase currently uses this but unsure if ALL 0x transactions are from Coinbase 
2. Changed price join logic to use priority eth prices table for base's ETH and WETH
3. Correct nft transfers docs
> add 0x model and nft transfers docs update

- .github/workflows/dbt_run_incremental_non_realtime.yml
- .github/workflows/dbt_run_streamline_chainhead.yml
- .github/workflows/dbt_run_streamline_decoder.yml
> refresh rate

- models/doc_descriptions/general/__overview__.md
- models/gold/core/core__ez_eth_transfers.sql
- models/gold/core/core__ez_eth_transfers.yml
- models/gold/core/core__ez_token_transfers.sql
- models/gold/core/core__ez_token_transfers.yml
1. Built ez eth/token transfers in core
2. Updated docs
3. Requires FR on deployment job
> AN-3981/ez-transfers-build

- models/doc_descriptions/dex - (imported from layer 1)/eth_ez_dex_swaps_table_doc.md
- models/gold/defi/defi__ez_dex_swaps.sql
- models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
- models/silver/defi/dex/voodoo/silver_dex__voodoo_swaps.sql
- models/silver/defi/dex/voodoo/silver_dex__voodoo_swaps.yml
edits on user submitted PR: https://github.com/FlipsideCrypto/base-models/pull/115 
1. Updated contract address to Vault (20k swaps) vs Router (14 swaps)
2. Requires `dbt run -m models/silver/defi/dex/voodoo/silver_dex__voodoo_swaps.sql+ --full-refresh`
> Voodoo-trade

- models/gold/core/core__fact_blocks.sql
- models/gold/core/core__fact_blocks.yml
- models/gold/core/core__fact_transactions.sql
- models/gold/core/core__fact_transactions.yml
- models/silver/core/silver__blocks.sql
- models/silver/core/silver__receipts.sql
- models/silver/core/silver__transactions.sql
`dbt run -m models/gold/core/core__fact_blocks.sql models/gold/core/core__fact_transactions.sql models/silver/core/silver__blocks.sql models/silver/core/silver__receipts.sql models/silver/core/silver__transactions.sql`
> withdrawals

- models/doc_descriptions/bridge/evm_bridge_activity.md
- models/gold/defi/defi__ez_bridge_activity.sql
- models/silver/defi/bridge/dln/silver_bridge__dln_debridge_createdorder.sql
- models/silver/defi/bridge/dln/silver_bridge__dln_debridge_createdorder.yml
- models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
1. Adds new bridge protocol
`dbt run -m models/silver/defi/bridge/dln/silver_bridge__dln_debridge_createdorder.sql --
full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql+ --var '{"HEAL_CURATED_MODEL":["dln_debridge"]}' `
> AN-4451/new-bridge

- models/silver/defi/lending/aave/silver__aave_tokens.sql
- models/silver/defi/lending/aave/silver__aave_tokens.yml
- models/silver/defi/lending/granary/silver__granary_tokens.sql
- models/silver/defi/lending/granary/silver__granary_tokens.yml
- models/silver/defi/lending/seamless/silver__seamless_tokens.sql
- models/silver/defi/lending/seamless/silver__seamless_tokens.yml
```
dbt run -m models/silver/defi/lending/seamless/silver__seamless_tokens.sql models/silver/defi/lending/granary/silver__granary_tokens.sql models/silver/defi/lending/aave/silver__aave_tokens.sql --full-refresh
```
> AN-4556/add-aave-token-model-tests

- models/silver/defi/dex/alienbase/silver_dex__alienbase_pools.sql
- models/silver/defi/dex/alienbase/silver_dex__alienbase_pools.yml
- models/silver/defi/dex/alienbase/silver_dex__alienbase_swaps.sql
- models/silver/defi/dex/alienbase/silver_dex__alienbase_swaps.yml
- models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql
- models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
`dbt run -m models/silver/defi/dex/alienbase --full-refresh && dbt run --vars '{"HEAL_CURATED_MODEL": ["alienbase","alienbase_swaps"]}' -m models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql models/silver/defi/dex/silver_dex__complete_dex_swaps.sql`
> AN-4486/add-new-higher-tvl-dexes

- models/silver/defi/lending/seamless/silver__seamless_tokens.sql
`dbt run -m models/silver/defi/lending/seamless/silver__seamless_tokens.sql --full-refresh`
> seamless-token-protocol-quick-fix 

- models/doc_descriptions/transfers/base_transfer_table_doc.md
- models/doc_descriptions/transfers/evm_transfers_table_doc.md
- models/gold/core/core__ez_native_transfers.yml
- models/gold/core/core__ez_token_transfers.yml
- models/gold/core/core__fact_token_transfers.yml
to capture docs updates in snowflake: `dbt run -m models/gold/core/core__ez_native_transfers.sql models/gold/core/core__ez_token_transfers.sql models/gold/core/core__fact_token_transfers.sql`
> AN-4879/transfers-docs

- models/gold/nft/nft__ez_nft_sales.yml
- models/silver/nft/sales/silver__complete_nft_sales.sql
- models/silver/nft/sales/silver__element_sales.sql
- models/silver/nft/sales/silver__element_sales.yml
- models/silver/nft/sales/silver__seaport_1_5_sales.sql
- models/silver/nft/sales/silver__seaport_1_6_sales.sql
- models/silver/nft/sales/silver__zeroex_sales.sql
Add element marketplace to Base
`dbt run -m models/silver/nft/sales/silver__element_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver__complete_nft_sales.sql --vars '{"HEAL_MODELS":["element"]}'`
> An 5039/element base

- package-lock.yml
- packages.yml
`dbt run -m models/github_actions`
> Update fsc utils version

- models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql
- models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.yml
- models/silver/defi/lending/morpho/silver__morpho_liquidations.sql
- models/silver/defi/lending/morpho/silver__morpho_liquidations.yml
`dbt run -m models/silver/defi/lending/morpho/silver__morpho_liquidations.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"morpho"}' -m models/silver/defi/lending/morpho/silver__morpho_liquidations.sql+`
> AN-5091/base-lending-bugs

- models/silver/defi/lending/aave/silver__aave_repayments.sql
`dbt run -m models/silver/protocols/aave/lending/silver__aave_repayments.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql`
> aave-repay-bug

- models/silver/defi/lending/aave/silver__aave_withdraws.sql
- models/silver/defi/lending/granary/silver__granary_repayments.sql
- models/silver/defi/lending/granary/silver__granary_withdraws.sql
- models/silver/defi/lending/seamless/silver__seamless_repayments.sql
- models/silver/defi/lending/seamless/silver__seamless_withdraws.sql
`dbt run -m models/silver/defi/lending/seamless/silver__seamless_repayments.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"seamless"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql`
> AN-5202/aave-fork-lending-bug

- models/silver/defi/dex/aerodrome/silver_dex__aerodrome_slipstream_pools.sql
- models/silver/defi/dex/aerodrome/silver_dex__aerodrome_slipstream_pools.yml
- models/silver/defi/dex/aerodrome/silver_dex__aerodrome_slipstream_swaps.sql
- models/silver/defi/dex/aerodrome/silver_dex__aerodrome_slipstream_swaps.yml
- models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql
- models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
`dbt run -m models/silver/defi/dex/aerodrome/silver_dex__aerodrome_slipstream_pools.sql models/silver/defi/dex/aerodrome/silver_dex__aerodrome_slipstream_swaps.sql && dbt run --vars '{"HEAL_MODELS":"aerodrome-slipstream"}' -m models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql models/silver/defi/dex/silver_dex__complete_dex_swaps.sql`
> AN-5261/add-aerodrome-slipstream-dex-swaps

- models/silver/defi/lending/moonwell/silver__moonwell_asset_details.sql
- models/silver/defi/lending/sonne/silver__sonne_asset_details.sql
`dbt run -m models/silver/defi/lending/moonwell --full-refresh -t dev-2xl && dbt run --vars '{"HEAL_MODELS":"moonwell"}' -m models/silver/defi/lending/complete_lending`
> AN-5257/moonwell-liquidation-issues 

- models/silver/protocols/vertex/silver__vertex_collateral.sql
- models/silver/protocols/vertex/silver__vertex_collateral.yml
`dbt run -m models/silver/protocols/vertex/silver__vertex_collateral.sql+ --full-refresh`
> base-vertex-collateral-fix

- models/silver/defi/lending/granary/silver__granary_tokens.sql
`dbt run -m models/silver/defi/lending/granary --full-refresh && dbt run --vars '{"HEAL_MODELS":"granary"}' -m models/silver/defi/lending/complete_lending`
> granary-new-token-name-structure

- models/silver/defi/lending/morpho/silver__morpho_liquidations.sql
`dbt run -m models/silver/defi/lending/morpho/silver__morpho_liquidations.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"morpho"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql`
> fix-morpho-liq-dupes

- models/doc_descriptions/general/__overview__.md
- models/doc_descriptions/vertex/vertex_column_docs.md
- models/doc_descriptions/vertex/vertex_table_docs.md
- models/gold/protocols/vertex/vertex__ez_money_markets.sql
- models/gold/protocols/vertex/vertex__ez_money_markets.yml
- models/silver/protocols/vertex/silver__vertex_money_markets.sql
- models/silver/protocols/vertex/silver__vertex_money_markets.yml
`dbt run -m models/silver/protocols/vertex/silver__vertex_money_markets.sql+`
> AN-5565/add-vertex-money-markets

- .github/workflows/dbt_run_traces_fix.yml
- models/silver/core/traces2_fix/silver__fact_traces2_fix.sql
`dbt run -m models/silver/core/traces2_fix/silver__fact_traces2_fix.sql --full-refresh`
> add fix for traces2

- data/github_actions__workflows.csv
`dbt seed -m data/github_actions__workflows.csv && dbt run -m models/github_actions --full-refresh && dbt run-operation fsc_utils.create_gha_tasks --vars '{"START_GHA_TASKS":True}'`
> push-non-realtime-curated-runs

- data/silver_bridge__cctp_chain_id_seed.csv
- models/gold/defi/defi__ez_bridge_activity.sql
- models/silver/defi/bridge/cctp/silver_bridge__cctp_depositforburn.sql
- models/silver/defi/bridge/cctp/silver_bridge__cctp_depositforburn.yml
- models/silver/defi/bridge/cctp/silver_bridge__cctp_v2_depositforburn.sql
- models/silver/defi/bridge/cctp/silver_bridge__cctp_v2_depositforburn.yml
- models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
- Added CCTP v1 v2 bridging and test files
- Added CCTP chain id seed file
- updated `complete_bridging_activity` with `circle-cctp` and `circle-cctp-v2`
- updated `defi__ez_bridge_activity` with `CCTP` in `meta`
```dbt seed --select silver_bridge__cctp_chain_id_seed && dbt run -m models/silver/defi/bridge/cctp/silver_bridge__cctp_depositforburn.sql models/silver/defi/bridge/cctp/silver_bridge__cctp_v2_depositforburn.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql --vars '{"HEAL_MODELS":["cctp","cctp_v2"]}'```
> add cctp v1 v2 

- models/silver/defi/lending/compound/silver__comp_asset_details.sql
`dbt run -m models/silver/defi/lending/compound --full-refresh && dbt run --vars '{"HEAL_MODELS":"comp"}' -m models/silver/defi/lending/complete_lending+`
> AN-6328/update-compv3-models

- models/silver/defi/lending/aave/silver__aave_tokens.sql
- models/silver/defi/lending/granary/silver__granary_tokens.sql
- models/silver/defi/lending/seamless/silver__seamless_tokens.sql
`dbt run -m models/silver/defi/lending/aave models/silver/defi/lending/granary models/silver/defi/lending/seamless --full-refresh && dbt run --vars '{"HEAL_MODELS":["aave","seamless","granary"]}' -m models/silver/defi/lending/complete_lending`
> AN-5443/aave-token-model-updates

- dbt_project.yml
- models/gold/defi/defi__ez_bridge_activity.sql
- models/gold/defi/defi__ez_bridge_activity.yml
- models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
- packages.yml
dbt seed && dbt run -m fsc_evm.curated_package.defi.bridge models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql models/gold/defi/defi__ez_bridge_activity.sql --full-refresh
> AN 5998 layerzero & stargate

- .github/workflows/dbt_run_scheduled_curated.yml
will remove in a week after backfill reads is done
> add everclear backfill run to curated workflow
